server {
    listen 80;
    listen [::]:80;
    server_name _;
    root /var/www/public;
    index index.php;
    charset utf-8;

    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        resolver 127.0.0.11 valid=10s ipv6=off;
        resolver_timeout 5s;
        set $fastcgi_upstream hmarket_app:9000;
        fastcgi_pass $fastcgi_upstream;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_read_timeout 300;
        fastcgi_next_upstream error timeout;
        fastcgi_next_upstream_tries 3;
    }
}
